import {
  ACTIVITY_FIELDS_LOGIC_ROLE,
  COMPANY_FIELDS_LOGIC_ROLE,
  LEAD_FIELDS_LOGIC_ROLE,
  OPPORTUNITY_FIELDS_LOGIC_ROLE,
} from '@bloobirds-it/types';

import { SALESFORCE } from '../../../../../../utils/integrations';

export enum defaultQuickFilters {
  FIRST_MEETING = 'FIRST_MEETING',
  FOLLOW_UP = 'FOLLOW_UP',
}

export const ACTIVITY_COLUMNS = [
  ACTIVITY_FIELDS_LOGIC_ROLE.REPORTED,
  ACTIVITY_FIELDS_LOGIC_ROLE.LEAD,
  ACTIVITY_FIELDS_LOGIC_ROLE.COMPANY,
  ACTIVITY_FIELDS_LOGIC_ROLE.TITLE,
  ACTIVITY_FIELDS_LOGIC_ROLE.USER,
  ACTIVITY_FIELDS_LOGIC_ROLE.MEETING_INVITEES,
  ACTIVITY_FIELDS_LOGIC_ROLE.NOTE,
  ACTIVITY_FIELDS_LOGIC_ROLE.MEETING_RESULT,
  ACTIVITY_FIELDS_LOGIC_ROLE.TIME,
  ACTIVITY_FIELDS_LOGIC_ROLE.CONFERENCING,
  ACTIVITY_FIELDS_LOGIC_ROLE.MEETING_MAIN_TYPE,
  ACTIVITY_FIELDS_LOGIC_ROLE.COPILOT_ANALYSIS,
  ACTIVITY_FIELDS_LOGIC_ROLE.BOT_ID,
  ACTIVITY_FIELDS_LOGIC_ROLE.TYPE,
];

export const REFERENCED_COLUMNS = [
  COMPANY_FIELDS_LOGIC_ROLE.NAME,
  COMPANY_FIELDS_LOGIC_ROLE.STATUS,
  COMPANY_FIELDS_LOGIC_ROLE.SALES_STATUS,
  COMPANY_FIELDS_LOGIC_ROLE.SALESFORCE_STATUS,
  COMPANY_FIELDS_LOGIC_ROLE.STAGE,
  COMPANY_FIELDS_LOGIC_ROLE.SOURCE,
  COMPANY_FIELDS_LOGIC_ROLE.TIME_ZONE,
  COMPANY_FIELDS_LOGIC_ROLE.COUNTRY,
  COMPANY_FIELDS_LOGIC_ROLE.LINKEDIN_URL,
  LEAD_FIELDS_LOGIC_ROLE.FULL_NAME,
  LEAD_FIELDS_LOGIC_ROLE.NAME,
  LEAD_FIELDS_LOGIC_ROLE.STATUS,
  LEAD_FIELDS_LOGIC_ROLE.SALES_STATUS,
  LEAD_FIELDS_LOGIC_ROLE.SALESFORCE_STATUS,
  LEAD_FIELDS_LOGIC_ROLE.STAGE,
  LEAD_FIELDS_LOGIC_ROLE.SOURCE,
  LEAD_FIELDS_LOGIC_ROLE.TIME_ZONE,
  LEAD_FIELDS_LOGIC_ROLE.LINKEDIN_URL,
  LEAD_FIELDS_LOGIC_ROLE.SALES_NAV_URL,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.NAME,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.PRIMARY_CONTACT,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.SALESFORCE_OPPORTUNITY_ID,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.SALESFORCE_STATUS,
  ACTIVITY_FIELDS_LOGIC_ROLE.TIME,
  SALESFORCE.OPPORTUNITY_ID_FIELD,
  SALESFORCE.CONTACT_ID_FIELD,
  SALESFORCE.LEAD_ID_FIELD,
  SALESFORCE.ACCOUNT_ID_FIELD,
];
