export enum FIELD_TYPES {
  TEXT = 'TEXT',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  DATE = 'DATE',
  DATETIME = 'DATETIME',
  URL = 'URL',
  REFERENCE = 'REFERENCE',
  PICKLIST = 'PICKLIST',
  GLOBAL_PICKLIST = 'GLOBAL_PICKLIST',
  MULTI_PICKLIST = 'MULTI_PICKLIST',
  MULTI_GLOBAL_PICKLIST = 'MULTI_GLOBAL_PICKLIST',
}
