export enum MIXPANEL_EVENTS {
  SCHEDULER_CLICK_ON_SLOT = 'SCHEDULER_CLICK_ON_OPTION_SLOT',
  SCHEDULER_SELECT_SLOT = 'SCHEDULER_SELECT_SLOT',
  SCHEDULER_CLICK_ON_ADD_GUESTS = 'SCHEDULER_CLICK_ON_ADD_GUESTS',
  SCHEDULER_SUBMIT_MEETING = 'SCHEDULER_SUBMIT_MEETING',
}
