name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish package and docs
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Grant private repo access
        run: echo "${{ secrets.NPMRC_GITHUB }}" > .npmrc
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@bloobirds-it"
      - name: Installing Dependencies
        run: yarn install --frozen-lockfile
      - name: Create semantic release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          branch: main
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'
      - name: Update manifest.json version
        uses: jossef/action-set-json-field@v2
        with:
          file: ./src/manifest.json
          field: version
          value: ${{ steps.version.outputs.value }}
      - name: Building Package
        run: yarn build
      - uses: vimtor/action-zip@v1
        with:
          files: dist/ manifest.json
          recursive: false
          dest: ./releases/bloobirds-chrome-extension-${{ steps.version.outputs.value }}.zip
      - name: Set the release
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}