// Generated by CodiumAI




/*
Code Analysis

Objective:
The objective of the "isAuth" function is to determine whether the app should be injected or not based on the hostname of the page.

Inputs:
- hostname: a string representing the hostname of the page.

Flow:
- Check if the hostname is equal to "localhost", "auth.bloobirds.com", or "auth.dev-bloobirds.com".
- If it is, return true.
- If it is not, return false.

Outputs:
- true: if the hostname is equal to "localhost", "auth.bloobirds.com", or "auth.dev-bloobirds.com".
- false: if the hostname is not equal to "localhost", "auth.bloobirds.com", or "auth.dev-bloobirds.com".

Additional aspects:
- The function is exported, which means it can be used in other modules.
- The function only checks for specific hostnames, which may need to be updated if new hostnames are added in the future.
*/



import { isAuth } from './auth.utils';

describe('isAuth_function', () => {

  // Tests that isAuth returns true when the hostname is localhost
  it("test_auth_localhost", () => {
    expect(isAuth('localhost')).toBe(true);
  });

  // Tests that isAuth returns true when the hostname is auth.bloobirds.com
  it("test_auth_bloobirds_com", () => {
    expect(isAuth('auth.bloobirds.com')).toBe(true);
  });

  // Tests that isAuth returns true when the hostname is auth.dev-bloobirds.com
  it("test_auth_dev_bloobirds_com", () => {
    expect(isAuth('auth.dev-bloobirds.com')).toBe(true);
  });

  // Tests that isAuth returns false when the hostname is not localhost, auth.bloobirds.com or auth.dev-bloobirds.com
  it("test_auth_other_hostname", () => {
    expect(isAuth('example.com')).toBe(false);
  });

  // Tests that isAuth returns false when the hostname is an empty string
  it("test_auth_empty_hostname", () => {
    expect(isAuth('')).toBe(false);
  });

});
