import {
  ACTIVITY_FIELDS_LOGIC_ROLE,
  BOBJECT_TYPES,
  COMPANY_FIELDS_LOGIC_ROLE,
  COMPANY_STATUS_LOGIC_ROLE,
  Direction,
  LEAD_FIELDS_LOGIC_ROLE,
  LEAD_STATUS_LOGIC_ROLE,
  OPPORTUNITY_FIELDS_LOGIC_ROLE,
  TASK_ACTION,
  TASK_FIELDS_LOGIC_ROLE,
} from '@bloobirds-it/types';

import { SALESFORCE } from '../../../../../../utils/integrations';

export const COMPANY_COLUMNS = [
  COMPANY_FIELDS_LOGIC_ROLE.HIGH_PRIORITY,
  COMPANY_FIELDS_LOGIC_ROLE.NAME,
  COMPANY_FIELDS_LOGIC_ROLE.NUMBER_OF_LEADS,
  COMPANY_FIELDS_LOGIC_ROLE.TARGET_MARKET,
  COMPANY_FIELDS_LOGIC_ROLE.STATUS,
  COMPANY_FIELDS_LOGIC_ROLE.STAGE,
  COMPANY_FIELDS_LOGIC_ROLE.SOURCE,
  COMPANY_FIELDS_LOGIC_ROLE.SALES_STATUS,
  COMPANY_FIELDS_LOGIC_ROLE.ASSIGNED_TO,
  COMPANY_FIELDS_LOGIC_ROLE.MR_RATING,
  COMPANY_FIELDS_LOGIC_ROLE.ASSIGNED_DATE,
  COMPANY_FIELDS_LOGIC_ROLE.UPDATE_DATETIME,
  COMPANY_FIELDS_LOGIC_ROLE.LINKEDIN_URL,
  COMPANY_FIELDS_LOGIC_ROLE.CADENCE,
  SALESFORCE.ACCOUNT_ID_FIELD,
];

export const LEAD_COLUMNS = [
  LEAD_FIELDS_LOGIC_ROLE.HIGH_PRIORITY,
  LEAD_FIELDS_LOGIC_ROLE.FULL_NAME,
  LEAD_FIELDS_LOGIC_ROLE.NAME,
  LEAD_FIELDS_LOGIC_ROLE.EMAIL,
  LEAD_FIELDS_LOGIC_ROLE.STATUS,
  LEAD_FIELDS_LOGIC_ROLE.SOURCE,
  LEAD_FIELDS_LOGIC_ROLE.STAGE,
  LEAD_FIELDS_LOGIC_ROLE.SALES_STATUS,
  LEAD_FIELDS_LOGIC_ROLE.ASSIGNED_TO,
  LEAD_FIELDS_LOGIC_ROLE.MR_RATING,
  LEAD_FIELDS_LOGIC_ROLE.ASSIGNED_DATE,
  LEAD_FIELDS_LOGIC_ROLE.LINKEDIN_URL,
  LEAD_FIELDS_LOGIC_ROLE.SALES_NAV_URL,
  LEAD_FIELDS_LOGIC_ROLE.ICP,
  LEAD_FIELDS_LOGIC_ROLE.COMPANY,
  LEAD_FIELDS_LOGIC_ROLE.UPDATE_DATETIME,
  LEAD_FIELDS_LOGIC_ROLE.ATTEMPTS_LAST_DAY,
  LEAD_FIELDS_LOGIC_ROLE.CADENCE,
  SALESFORCE.LEAD_ID_FIELD,
  SALESFORCE.CONTACT_ID_FIELD,
];

export const LEAD_REFERENCED_COLUMNS = [
  COMPANY_FIELDS_LOGIC_ROLE.NAME,
  LEAD_FIELDS_LOGIC_ROLE.STAGE,
  COMPANY_FIELDS_LOGIC_ROLE.STATUS,
];

export const TASK_COLUMNS = [
  TASK_FIELDS_LOGIC_ROLE.TITLE,
  TASK_FIELDS_LOGIC_ROLE.STATUS,
  TASK_FIELDS_LOGIC_ROLE.COMPANY,
  TASK_FIELDS_LOGIC_ROLE.LEAD,
  TASK_FIELDS_LOGIC_ROLE.OPPORTUNITY,
  TASK_FIELDS_LOGIC_ROLE.ASSIGNED_TO,
  TASK_FIELDS_LOGIC_ROLE.SCHEDULED_DATE,
  TASK_FIELDS_LOGIC_ROLE.SCHEDULED_DATETIME,
  TASK_FIELDS_LOGIC_ROLE.TASK_TYPE,
  TASK_FIELDS_LOGIC_ROLE.IS_AUTOMATED,
  TASK_FIELDS_LOGIC_ROLE.IS_AUTOMATED_EMAIL,
  TASK_FIELDS_LOGIC_ROLE.DESCRIPTION,
  TASK_ACTION.CALL,
  TASK_ACTION.EMAIL,
  TASK_ACTION.LINKEDIN_MESSAGE,
  TASK_FIELDS_LOGIC_ROLE.CADENCE,
  TASK_FIELDS_LOGIC_ROLE.MEETING_ACTIVITY,
  TASK_FIELDS_LOGIC_ROLE.PRIORITY,
];
export const TASK_REFERENCED_COLUMNS = [
  COMPANY_FIELDS_LOGIC_ROLE.NAME,
  COMPANY_FIELDS_LOGIC_ROLE.EMAIL,
  COMPANY_FIELDS_LOGIC_ROLE.STATUS,
  COMPANY_FIELDS_LOGIC_ROLE.SOURCE,
  COMPANY_FIELDS_LOGIC_ROLE.STAGE,
  COMPANY_FIELDS_LOGIC_ROLE.TIME_ZONE,
  COMPANY_FIELDS_LOGIC_ROLE.COUNTRY,
  COMPANY_FIELDS_LOGIC_ROLE.CADENCE,
  COMPANY_FIELDS_LOGIC_ROLE.ATTEMPTS_LAST_DAY,
  COMPANY_FIELDS_LOGIC_ROLE.HIGH_PRIORITY,
  COMPANY_FIELDS_LOGIC_ROLE.NURTURING_REASONS,
  COMPANY_FIELDS_LOGIC_ROLE.LINKEDIN_URL,
  LEAD_FIELDS_LOGIC_ROLE.FULL_NAME,
  LEAD_FIELDS_LOGIC_ROLE.EMAIL,
  LEAD_FIELDS_LOGIC_ROLE.STATUS,
  LEAD_FIELDS_LOGIC_ROLE.SOURCE,
  LEAD_FIELDS_LOGIC_ROLE.STAGE,
  LEAD_FIELDS_LOGIC_ROLE.CADENCE,
  LEAD_FIELDS_LOGIC_ROLE.ATTEMPTS_LAST_DAY,
  LEAD_FIELDS_LOGIC_ROLE.HIGH_PRIORITY,
  LEAD_FIELDS_LOGIC_ROLE.NURTURING_REASONS,
  LEAD_FIELDS_LOGIC_ROLE.LINKEDIN_URL,
  ACTIVITY_FIELDS_LOGIC_ROLE.TIME,
];

export const OPPORTUNITY_COLUMNS = [
  OPPORTUNITY_FIELDS_LOGIC_ROLE.AMOUNT,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.ASSIGNED_TO,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.CLOSE_DATE,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.COMPANY,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.NAME,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.STATUS__LAST_UPDATE,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.STATUS,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.UPDATE_DATETIME,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.ATTEMPTS_LAST_DAY,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.CREATION_DATETIME,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.EXTRA_INFO_ACTIVITY,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.EXTRA_INFO_ACTIVITY_DATE,
  OPPORTUNITY_FIELDS_LOGIC_ROLE.EXTRA_INFO_TASK_DATE,
  SALESFORCE.OPPORTUNITY_ID_FIELD,
];

export const OPPORTUNITY_REFERENCED_COLUMNS = [
  COMPANY_FIELDS_LOGIC_ROLE.NAME,
  COMPANY_FIELDS_LOGIC_ROLE.STATUS,
];

export const COLUMNS_BY_BOBJECT_TYPE = {
  [BOBJECT_TYPES.OPPORTUNITY]: OPPORTUNITY_COLUMNS,
  [BOBJECT_TYPES.LEAD]: LEAD_COLUMNS,
  [BOBJECT_TYPES.COMPANY]: COMPANY_COLUMNS,
  [BOBJECT_TYPES.TASK]: TASK_COLUMNS,
};

export const COLUMNS_REFERENCED_BY_BOBJECT_TYPE = {
  [BOBJECT_TYPES.OPPORTUNITY]: OPPORTUNITY_REFERENCED_COLUMNS,
  [BOBJECT_TYPES.TASK]: TASK_REFERENCED_COLUMNS,
};

export const COLUMN_SORT_BY_BOBJECT_TYPE = {
  [BOBJECT_TYPES.OPPORTUNITY]: OPPORTUNITY_FIELDS_LOGIC_ROLE.UPDATE_DATETIME,
  [BOBJECT_TYPES.COMPANY]: COMPANY_FIELDS_LOGIC_ROLE.ASSIGNED_DATE,
  [BOBJECT_TYPES.LEAD]: LEAD_FIELDS_LOGIC_ROLE.ASSIGNED_DATE,
};

export const getSortFields = bobjectType => ({
  lastAssigned: {
    field: COLUMN_SORT_BY_BOBJECT_TYPE[bobjectType],
    direction: Direction.DESC,
  },
  recentAssigned: {
    field: COLUMN_SORT_BY_BOBJECT_TYPE[bobjectType],
    direction: Direction.ASC,
  },
  lastUpdateRecent: {
    field: COLUMN_SORT_BY_BOBJECT_TYPE[bobjectType],
    direction: Direction.DESC,
  },
  lastUpdateOldest: {
    field: COLUMN_SORT_BY_BOBJECT_TYPE[bobjectType],
    direction: Direction.ASC,
  },
});

export const INACTIVE_FIELDS_LOGIC_ROLE = {
  [BOBJECT_TYPES.COMPANY]: COMPANY_FIELDS_LOGIC_ROLE.IS_INACTIVE,
  [BOBJECT_TYPES.LEAD]: LEAD_FIELDS_LOGIC_ROLE.IS_INACTIVE,
  [BOBJECT_TYPES.OPPORTUNITY]: OPPORTUNITY_FIELDS_LOGIC_ROLE.IS_INACTIVE,
};

export const INACTIVE_YES_FIELDS_LOGIC_ROLE = {
  [BOBJECT_TYPES.COMPANY]: 'COMPANY__IS_INACTIVE__YES',
  [BOBJECT_TYPES.LEAD]: 'LEAD__IS_INACTIVE__YES',
  [BOBJECT_TYPES.OPPORTUNITY]: 'OPPORTUNITY__IS_INACTIVE__YES',
};

export const STATUS_FIELDS_LOGIC_ROLE = {
  [BOBJECT_TYPES.COMPANY]: COMPANY_FIELDS_LOGIC_ROLE.STATUS,
  [BOBJECT_TYPES.LEAD]: LEAD_FIELDS_LOGIC_ROLE.STATUS,
};

export const STATUS_VALUES_LOGIC_ROLE = {
  [BOBJECT_TYPES.COMPANY]: [
    COMPANY_STATUS_LOGIC_ROLE.ON_PROSPECTION,
    COMPANY_STATUS_LOGIC_ROLE.CONTACTED,
    COMPANY_STATUS_LOGIC_ROLE.ENGAGED,
    COMPANY_STATUS_LOGIC_ROLE.NURTURING,
    COMPANY_STATUS_LOGIC_ROLE.MEETING,
  ],
  [BOBJECT_TYPES.LEAD]: [
    LEAD_STATUS_LOGIC_ROLE.ON_PROSPECTION,
    LEAD_STATUS_LOGIC_ROLE.CONTACTED,
    LEAD_STATUS_LOGIC_ROLE.ENGAGED,
    LEAD_STATUS_LOGIC_ROLE.NURTURING,
    LEAD_STATUS_LOGIC_ROLE.MEETING,
  ],
};

export const SALES_STATUS_FIELDS_LOGIC_ROLE = {
  [BOBJECT_TYPES.COMPANY]: COMPANY_FIELDS_LOGIC_ROLE.SALES_STATUS,
  [BOBJECT_TYPES.LEAD]: LEAD_FIELDS_LOGIC_ROLE.SALES_STATUS,
  [BOBJECT_TYPES.OPPORTUNITY]: OPPORTUNITY_FIELDS_LOGIC_ROLE.STATUS,
};
