import { getLocationFromTimeZone } from './scheduleEmailModal.utils';
import spacetime from 'spacetime';

const timezones = {
  'UTC - 03_00 America/Glace Bay': 'America/Glace_Bay',
  'UTC + 00:00 Africa/Abidjan': 'Africa/Abidjan',
  'UTC + 00:00 Africa/Accra': 'Africa/Accra',
  'UTC + 03:00 Africa/Addis Ababa': 'Africa/Addis_Ababa',
  'UTC + 01:00 Africa/Algiers': 'Africa/Algiers',
  'UTC + 03:00 Africa/Asmara': 'Africa/Asmara',
  'UTC + 00:00 Africa/Bamako': 'Africa/Bamako',
  'UTC + 01:00 Africa/Bangui': 'Africa/Bangui',
  'UTC + 00:00 Africa/Banjul': 'Africa/Banjul',
  'UTC + 00:00 Africa/Bissau': 'Africa/Bissau',
  'UTC + 02:00 Africa/Blantyre': 'Africa/Blantyre',
  'UTC + 01:00 Africa/Brazzaville': 'Africa/Brazzaville',
  'UTC + 02:00 Africa/Bujumbura': 'Africa/Bujumbura',
  'UTC + 02:00 Africa/Cairo': 'Africa/Cairo',
  'UTC - 04:00 America/Antigua': 'America/Antigua',
  'UTC - 03:00 America/Araguaina': 'America/Araguaina',
  'UTC - 04:00 America/Aruba': 'America/Aruba',
  'UTC - 03:00 America/Asuncion': 'America/Asuncion',
  'UTC - 05:00 America/Atikokan': 'America/Atikokan',
  'UTC - 09:00 America/Atka': 'America/Atka',
  'UTC - 03:00 America/Bahia': 'America/Bahia',
  'UTC - 04:00 America/Barbados': 'America/Barbados',
  'UTC - 03:00 America/Belem': 'America/Belem',
  'UTC - 06:00 America/Belize': 'America/Belize',
  'UTC - 04:00 America/Blanc-Sablon': 'America/Blanc-Sablon',
  'UTC - 04:00 America/Boa Vista': 'America/Boa_Vista',
  'UTC - 05:00 America/Bogota': 'America/Bogota',
  'UTC - 06:00 America/Boise': 'America/Boise',
  'UTC - 03:00 America/Buenos Aires': 'America/Buenos_Aires',
  'UTC - 06:00 America/Cambridge Bay': 'America/Cambridge_Bay',
  'UTC - 04:00 America/Campo Grande': 'America/Campo_Grande',
  'UTC - 06:00 America/Cancun': 'America/Cancun',
  'UTC - 04:00 America/Caracas': 'America/Caracas',
  'UTC - 03:00 America/Catamarca': 'America/Catamarca',
  'UTC - 03:00 America/Cayenne': 'America/Cayenne',
  'UTC - 05:00 America/Cayman': 'America/Cayman',
  'UTC - 05:00 America/Chicago': 'America/Chicago',
  'UTC - 07:00 America/Chihuahua': 'America/Chihuahua',
  'UTC - 05:00 America/Coral Harbour': 'America/Coral_Harbour',
  'UTC - 03:00 America/Cordoba': 'America/Cordoba',
  'UTC - 06:00 America/Costa Rica': 'America/Costa_Rica',
  'UTC - 04:00 America/Cuiaba': 'America/Cuiaba',
  'UTC - 04:00 America/Curacao': 'America/Curacao',
  'UTC + 00:00 America/Danmarkshavn': 'America/Danmarkshavn',
  'UTC - 07:00 America/Dawson': 'America/Dawson',
  'UTC - 07:00 America/Dawson Creek': 'America/Dawson_Creek',
  'UTC - 06:00 America/Denver': 'America/Denver',
  'UTC - 04:00 America/Detroit': 'America/Detroit',
  'UTC - 04:00 America/Dominica': 'America/Dominica',
  'UTC - 06:00 America/Edmonton': 'America/Edmonton',
  'UTC + 00:00 Africa/Casablanca': 'Africa/Casablanca',
  'UTC + 01:00 Africa/Ceuta': 'Africa/Ceuta',
  'UTC + 00:00 Africa/Conakry': 'Africa/Conakry',
  'UTC + 00:00 Africa/Dakar': 'Africa/Dakar',
  'UTC + 03:00 Africa/Dar es Salaam': 'Africa/Dar_es_Salaam',
  'UTC + 03:00 Africa/Djibouti': 'Africa/Djibouti',
  'UTC + 01:00 Africa/Douala': 'Africa/Douala',
  'UTC + 00:00 Africa/El Aaiun': 'Africa/El_Aaiun',
  'UTC + 00:00 Africa/Freetown': 'Africa/Freetown',
  'UTC + 02:00 Africa/Gaborone': 'Africa/Gaborone',
  'UTC + 02:00 Africa/Harare': 'Africa/Harare',
  'UTC + 02:00 Africa/Johannesburg': 'Africa/Johannesburg',
  'UTC + 03:00 Africa/Kampala': 'Africa/Kampala',
  'UTC + 03:00 Africa/Khartoum': 'Africa/Khartoum',
  'UTC + 02:00 Africa/Kigali': 'Africa/Kigali',
  'UTC + 01:00 Africa/Kinshasa': 'Africa/Kinshasa',
  'UTC + 01:00 Africa/Lagos': 'Africa/Lagos',
  'UTC + 01:00 Africa/Libreville': 'Africa/Libreville',
  'UTC + 00:00 Africa/Lome': 'Africa/Lome',
  'UTC + 01:00 Africa/Luanda': 'Africa/Luanda',
  'UTC + 02:00 Africa/Lubumbashi': 'Africa/Lubumbashi',
  'UTC + 02:00 Africa/Lusaka': 'Africa/Lusaka',
  'UTC + 01:00 Africa/Malabo': 'Africa/Malabo',
  'UTC + 02:00 Africa/Maputo': 'Africa/Maputo',
  'UTC + 02:00 Africa/Maseru': 'Africa/Maseru',
  'UTC + 02:00 Africa/Mbabane': 'Africa/Mbabane',
  'UTC + 03:00 Africa/Mogadishu': 'Africa/Mogadishu',
  'UTC + 00:00 Africa/Monrovia': 'Africa/Monrovia',
  'UTC + 03:00 Africa/Nairobi': 'Africa/Nairobi',
  'UTC + 01:00 Africa/Ndjamena': 'Africa/Ndjamena',
  'UTC + 01:00 Africa/Niamey': 'Africa/Niamey',
  'UTC + 00:00 Africa/Nouakchott': 'Africa/Nouakchott',
  'UTC + 00:00 Africa/Ouagadougou': 'Africa/Ouagadougou',
  'UTC + 01:00 Africa/Porto-Novo': 'Africa/Porto-Novo',
  'UTC + 00:00 Africa/Sao Tome': 'Africa/Sao_Tome',
  'UTC + 00:00 Africa/Timbuktu': 'Africa/Timbuktu',
  'UTC + 02:00 Africa/Tripoli': 'Africa/Tripoli',
  'UTC + 01:00 Africa/Tunis': 'Africa/Tunis',
  'UTC + 02:00 Africa/Windhoek': 'Africa/Windhoek',
  'UTC - 09:00 America/Adak': 'America/Adak',
  'UTC - 08:00 America/Anchorage': 'America/Anchorage',
  'UTC - 04:00 America/Anguilla': 'America/Anguilla',
  'UTC - 05:00 America/Eirunepe': 'America/Eirunepe',
  'UTC - 06:00 America/El Salvador': 'America/El_Salvador',
  'UTC - 08:00 America/Ensenada': 'America/Ensenada',
  'UTC - 04:00 America/Fort Wayne': 'America/Fort_Wayne',
  'UTC - 03:00 America/Fortaleza': 'America/Fortaleza',
  'UTC - 02:00 America/Noronha': 'America/Noronha',
  'UTC - 03:00 America/Godthab': 'America/Godthab',
  'UTC - 05:00 America/Panama': 'America/Panama',
  'UTC - 03:00 America/Goose Bay': 'America/Goose_Bay',
  'UTC - 04:00 America/Pangnirtung': 'America/Pangnirtung',
  'UTC - 04:00 America/Grand Turk': 'America/Grand_Turk',
  'UTC - 03:00 America/Paramaribo': 'America/Paramaribo',
  'UTC - 04:00 America/Grenada': 'America/Grenada',
  'UTC - 07:00 America/Phoenix': 'America/Phoenix',
  'UTC - 04:00 America/Guadeloupe': 'America/Guadeloupe',
  'UTC - 04:00 America/Port of Spain': 'America/Port_of_Spain',
  'UTC - 06:00 America/Guatemala': 'America/Guatemala',
  'UTC - 05:00 America/Porto Acre': 'America/Porto_Acre',
  'UTC - 05:00 America/Guayaquil': 'America/Guayaquil',
  'UTC - 04:00 America/Porto Velho': 'America/Porto_Velho',
  'UTC - 04:00 America/Guyana': 'America/Guyana',
  'UTC - 04:00 America/Puerto Rico': 'America/Puerto_Rico',
  'UTC - 03:00 America/Halifax': 'America/Halifax',
  'UTC - 05:00 America/Rainy River': 'America/Rainy_River',
  'UTC - 04:00 America/Havana': 'America/Havana',
  'UTC - 05:00 America/Rankin Inlet': 'America/Rankin_Inlet',
  'UTC - 03:00 America/Recife': 'America/Recife',
  'UTC - 07:00 America/Hermosillo': 'America/Hermosillo',
  'UTC - 06:00 America/Regina': 'America/Regina',
  'UTC - 04:00 America/Indianapolis': 'America/Indianapolis',
  'UTC - 05:00 America/Resolute': 'America/Resolute',
  'UTC - 06:00 America/Inuvik': 'America/Inuvik',
  'UTC - 05:00 America/Rio Branco': 'America/Rio_Branco',
  'UTC - 03:00 America/Rosario': 'America/Rosario',
  'UTC - 04:00 America/Iqaluit': 'America/Iqaluit',
  'UTC - 03:00 America/Santiago': 'America/Santiago',
  'UTC - 05:00 America/Jamaica': 'America/Jamaica',
  'UTC - 04:00 America/Santo Domingo': 'America/Santo_Domingo',
  'UTC - 03:00 America/Jujuy': 'America/Jujuy',
  'UTC - 03:00 America/Sao Paulo': 'America/Sao_Paulo',
  'UTC - 01:00 America/Scoresbysund': 'America/Scoresbysund',
  'UTC - 08:00 America/Juneau': 'America/Juneau',
  'UTC - 06:00 America/Shiprock': 'America/Shiprock',
  'UTC - 02:30 America/St Johns': 'America/St_Johns',
  'UTC - 04:00 America/La Paz': 'America/La_Paz',
  'UTC - 04:00 America/St Kitts': 'America/St_Kitts',
  'UTC - 04:00 America/St Lucia': 'America/St_Lucia',
  'UTC - 05:00 America/Lima': 'America/Lima',
  'UTC - 04:00 America/St Thomas': 'America/St_Thomas',
  'UTC - 07:00 America/Los Angeles': 'America/Los_Angeles',
  'UTC - 04:00 America/St Vincent': 'America/St_Vincent',
  'UTC - 04:00 America/Louisville': 'America/Louisville',
  'UTC - 06:00 America/Swift Current': 'America/Swift_Current',
  'UTC - 03:00 America/Maceio': 'America/Maceio',
  'UTC - 06:00 America/Tegucigalpa': 'America/Tegucigalpa',
  'UTC - 06:00 America/Managua': 'America/Managua',
  'UTC - 03:00 America/Thule': 'America/Thule',
  'UTC - 04:00 America/Manaus': 'America/Manaus',
  'UTC - 04:00 America/Thunder Bay': 'America/Thunder_Bay',
  'UTC - 04:00 America/Martinique': 'America/Martinique',
  'UTC - 08:00 America/Tijuana': 'America/Tijuana',
  'UTC - 04:00 America/Toronto': 'America/Toronto',
  'UTC - 07:00 America/Mazatlan': 'America/Mazatlan',
  'UTC - 04:00 America/Tortola': 'America/Tortola',
  'UTC - 03:00 America/Mendoza': 'America/Mendoza',
  'UTC - 07:00 America/Vancouver': 'America/Vancouver',
  'UTC - 05:00 America/Menominee': 'America/Menominee',
  'UTC - 04:00 America/Virgin': 'America/Virgin',
  'UTC - 06:00 America/Merida': 'America/Merida',
  'UTC - 07:00 America/Whitehorse': 'America/Whitehorse',
  'UTC - 06:00 America/Mexico City': 'America/Mexico_City',
  'UTC - 05:00 America/Winnipeg': 'America/Winnipeg',
  'UTC - 02:00 America/Miquelon': 'America/Miquelon',
  'UTC - 08:00 America/Yakutat': 'America/Yakutat',
  'UTC - 03:00 America/Moncton': 'America/Moncton',
  'UTC + 08:00 Antarctica/Casey': 'Antarctica/Casey',
  'UTC + 07:00 Antarctica/Davis': 'Antarctica/Davis',
  'UTC - 06:00 America/Yellowknife': 'America/Yellowknife',
  'UTC - 06:00 America/Monterrey': 'America/Monterrey',
  'UTC + 06:00 Antarctica/Mawson': 'Antarctica/Mawson',
  'UTC - 02:00 America/Montevideo': 'America/Montevideo',
  'UTC + 13:00 Antarctica/McMurdo': 'Antarctica/McMurdo',
  'UTC - 04:00 America/Montreal': 'America/Montreal',
  'UTC - 03:00 Antarctica/Palmer': 'Antarctica/Palmer',
  'UTC - 04:00 America/Montserrat': 'America/Montserrat',
  'UTC - 04:00 America/Nassau': 'America/Nassau',
  'UTC - 03:00 Antarctica/Rothera': 'Antarctica/Rothera',
  'UTC + 13:00 Antarctica/Rothera': 'Antarctica/Rothera',
  'UTC - 04:00 America/New York': 'America/New_York',
  'UTC + 03:00 Antarctica/Syowa': 'Antarctica/Syowa',
  'UTC + 06:00 Antarctica/Vostok': 'Antarctica/Vostok',
  'UTC - 04:00 America/Nipigon': 'America/Nipigon',
  'UTC + 03:00 Asia/Aden': 'Asia/Aden',
  'UTC - 08:00 America/Nome': 'America/Nome',
  'UTC + 06:00 Asia/Almaty': 'Asia/Almaty',
  'UTC + 03:00 Europe/Volgograd': 'Europe/Volgograd',
  'UTC + 02:00 Asia/Amman': 'Asia/Amman',
  'UTC + 12:00 Asia/Anadyr': 'Asia/Anadyr',
  'UTC + 05:00 Asia/Aqtau': 'Asia/Aqtau',
  'UTC + 05:00 Asia/Aqtobe': 'Asia/Aqtobe',
  'UTC + 05:00 Asia/Ashgabat': 'Asia/Ashgabat',
  'UTC + 05:00 Asia/Ashkhabad': 'Asia/Ashkhabad',
  'UTC + 03:00 Asia/Baghdad': 'Asia/Baghdad',
  'UTC + 03:00 Asia/Bahrain': 'Asia/Bahrain',
  'UTC + 04:00 Asia/Baku': 'Asia/Baku',
  'UTC + 07:00 Asia/Bangkok': 'Asia/Bangkok',
  'UTC + 02:00 Asia/Beirut': 'Asia/Beirut',
  'UTC + 06:00 Asia/Bishkek': 'Asia/Bishkek',
  'UTC + 08:00 Asia/Brunei': 'Asia/Brunei',
  'UTC + 05:30 Asia/Calcutta': 'Asia/Calcutta',
  'UTC + 09:00 Asia/Choibalsan': 'Asia/Choibalsan',
  'UTC + 08:00 Asia/Chongqing': 'Asia/Chongqing',
  'UTC + 08:00 Asia/Chungking': 'Asia/Chungking',
  'UTC + 05:30 Asia/Colombo': 'Asia/Colombo',
  'UTC + 06:00 Asia/Dacca': 'Asia/Dacca',
  'UTC + 02:00 Asia/Damascus': 'Asia/Damascus',
  'UTC + 06:00 Asia/Dhaka': 'Asia/Dhaka',
  'UTC + 09:00 Asia/Dili': 'Asia/Dili',
  'UTC + 04:00 Asia/Dubai': 'Asia/Dubai',
  'UTC + 05:00 Asia/Dushanbe': 'Asia/Dushanbe',
  'UTC + 02:00 Asia/Gaza': 'Asia/Gaza',
  'UTC + 08:00 Asia/Harbin': 'Asia/Harbin',
  'UTC + 08:00 Asia/Hong Kong': 'Asia/Hong_Kong',
  'UTC + 07:00 Asia/Hovd': 'Asia/Hovd',
  'UTC + 08:00 Asia/Irkutsk': 'Asia/Irkutsk',
  'UTC + 02:00 Asia/Istanbul': 'Asia/Istanbul',
  'UTC + 07:00 Asia/Jakarta': 'Asia/Jakarta',
  'UTC + 08:00 Asia/Ulaanbaatar': 'Asia/Ulaanbaatar',
  'UTC + 08:00 Asia/Ulan Bator': 'Asia/Ulan_Bator',
  'UTC + 08:00 Asia/Urumqi': 'Asia/Urumqi',
  'UTC + 07:00 Asia/Vientiane': 'Asia/Vientiane',
  'UTC + 10:00 Asia/Vladivostok': 'Asia/Vladivostok',
  'UTC + 09:00 Asia/Yakutsk': 'Asia/Yakutsk',
  'UTC + 05:00 Asia/Yekaterinburg': 'Asia/Yekaterinburg',
  'UTC + 04:00 Asia/Yerevan': 'Asia/Yerevan',
  'UTC + 11:00 Australia/ACT': 'Australia/ACT',
  'UTC + 10:30 Australia/Adelaide': 'Australia/Adelaide',
  'UTC + 10:00 Australia/Brisbane': 'Australia/Brisbane',
  'UTC + 10:30 Australia/Broken Hill': 'Australia/Broken_Hill',
  'UTC + 11:00 Australia/Canberra': 'Australia/Canberra',
  'UTC + 11:00 Australia/Currie': 'Australia/Currie',
  'UTC + 09:30 Australia/Darwin': 'Australia/Darwin',
  'UTC + 09:45 Australia/Eucla': 'Australia/Eucla',
  'UTC + 11:00 Australia/Hobart': 'Australia/Hobart',
  'UTC + 11:00 Australia/LHI': 'Australia/LHI',
  'UTC + 10:00 Australia/Lindeman': 'Australia/Lindeman',
  'UTC + 11:00 Australia/Lord Howe': 'Australia/Lord_Howe',
  'UTC + 11:00 Australia/Melbourne': 'Australia/Melbourne',
  'UTC + 09:30 Australia/North': 'Australia/North',
  'UTC + 09:00 Australia/Perth': 'Australia/Perth',
  'UTC + 10:00 Australia/Queensland': 'Australia/Queensland',
  'UTC + 10:30 Australia/South': 'Australia/South',
  'UTC + 11:00 Australia/Sydney': 'Australia/Sydney',
  'UTC + 11:00 Australia/Tasmania': 'Australia/Tasmania',
  'UTC + 11:00 Australia/Victoria': 'Australia/Victoria',
  'UTC + 09:00 Australia/West': 'Australia/West',
  'UTC + 10:30 Australia/Yancowinna': 'Australia/Yancowinna',
  'UTC + 01:00 Europe/Amsterdam': 'Europe/Amsterdam',
  'UTC + 09:00 Asia/Jayapura': 'Asia/Jayapura',
  'UTC + 02:00 Asia/Jerusalem': 'Asia/Jerusalem',
  'UTC + 04:30 Asia/Kabul': 'Asia/Kabul',
  'UTC + 12:00 Asia/Kamchatka': 'Asia/Kamchatka',
  'UTC + 05:00 Asia/Karachi': 'Asia/Karachi',
  'UTC + 08:00 Asia/Kashgar': 'Asia/Kashgar',
  'UTC + 05:45 Asia/Katmandu': 'Asia/Katmandu',
  'UTC + 07:00 Asia/Krasnoyarsk': 'Asia/Krasnoyarsk',
  'UTC + 08:00 Asia/Kuala Lumpur': 'Asia/Kuala_Lumpur',
  'UTC + 08:00 Asia/Kuching': 'Asia/Kuching',
  'UTC + 03:00 Asia/Kuwait': 'Asia/Kuwait',
  'UTC + 08:00 Asia/Macao': 'Asia/Macao',
  'UTC + 08:00 Asia/Macau': 'Asia/Macau',
  'UTC + 11:00 Asia/Magadan': 'Asia/Magadan',
  'UTC + 08:00 Asia/Makassar': 'Asia/Makassar',
  'UTC + 08:00 Asia/Manila': 'Asia/Manila',
  'UTC + 04:00 Asia/Muscat': 'Asia/Muscat',
  'UTC + 02:00 Asia/Nicosia': 'Asia/Nicosia',
  'UTC + 06:00 Asia/Novosibirsk': 'Asia/Novosibirsk',
  'UTC + 06:00 Asia/Omsk': 'Asia/Omsk',
  'UTC + 05:00 Asia/Oral': 'Asia/Oral',
  'UTC + 07:00 Asia/Phnom Penh': 'Asia/Phnom_Penh',
  'UTC + 07:00 Asia/Pontianak': 'Asia/Pontianak',
  'UTC + 09:00 Asia/Pyongyang': 'Asia/Pyongyang',
  'UTC + 03:00 Asia/Qatar': 'Asia/Qatar',
  'UTC + 06:00 Asia/Qyzylorda': 'Asia/Qyzylorda',
  'UTC + 06:30 Asia/Rangoon': 'Asia/Rangoon',
  'UTC + 03:00 Asia/Riyadh': 'Asia/Riyadh',
  'UTC + 07:00 Asia/Saigon': 'Asia/Saigon',
  'UTC + 10:00 Asia/Sakhalin': 'Asia/Sakhalin',
  'UTC + 05:00 Asia/Samarkand': 'Asia/Samarkand',
  'UTC + 09:00 Asia/Seoul': 'Asia/Seoul',
  'UTC + 08:00 Asia/Shanghai': 'Asia/Shanghai',
  'UTC + 08:00 Asia/Singapore': 'Asia/Singapore',
  'UTC + 08:00 Asia/Taipei': 'Asia/Taipei',
  'UTC + 05:00 Asia/Tashkent': 'Asia/Tashkent',
  'UTC + 04:00 Asia/Tbilisi': 'Asia/Tbilisi',
  'UTC + 03:30 Asia/Tehran': 'Asia/Tehran',
  'UTC + 02:00 Asia/Tel Aviv': 'Asia/Tel_Aviv',
  'UTC + 06:00 Asia/Thimbu': 'Asia/Thimbu',
  'UTC + 06:00 Asia/Thimphu': 'Asia/Thimphu',
  'UTC + 09:00 Asia/Tokyo': 'Asia/Tokyo',
  'UTC + 08:00 Asia/Ujung Pandang': 'Asia/Ujung_Pandang',
  'UTC + 01:00 Europe/Copenhagen': 'Europe/Copenhagen',
  'UTC + 00:00 Europe/Dublin': 'Europe/Dublin',
  'UTC + 01:00 Europe/Gibraltar': 'Europe/Gibraltar',
  'UTC + 00:00 Europe/Guernsey': 'Europe/Guernsey',
  'UTC + 02:00 Europe/Helsinki': 'Europe/Helsinki',
  'UTC + 00:00 Europe/Isle of Man': 'Europe/Isle_of_Man',
  'UTC + 02:00 Europe/Istanbul': 'Europe/Istanbul',
  'UTC + 00:00 Europe/Jersey': 'Europe/Jersey',
  'UTC + 02:00 Europe/Kaliningrad': 'Europe/Kaliningrad',
  'UTC + 02:00 Europe/Kiev': 'Europe/Kiev',
  'UTC + 00:00 Europe/Lisbon': 'Europe/Lisbon',
  'UTC + 01:00 Europe/Ljubljana': 'Europe/Ljubljana',
  'UTC + 00:00 Europe/London': 'Europe/London',
  'UTC + 01:00 Europe/Luxembourg': 'Europe/Luxembourg',
  'UTC + 01:00 Europe/Madrid': 'Europe/Madrid',
  'UTC + 01:00 Europe/Malta': 'Europe/Malta',
  'UTC + 01:00 Europe/Mariehamn': 'Europe/Mariehamn',
  'UTC + 02:00 Europe/Minsk': 'Europe/Minsk',
  'UTC + 01:00 Europe/Monaco': 'Europe/Monaco',
  'UTC + 03:00 Europe/Moscow': 'Europe/Moscow',
  'UTC + 02:00 Europe/Nicosia': 'Europe/Nicosia',
  'UTC + 01:00 Europe/Oslo': 'Europe/Oslo',
  'UTC + 01:00 Europe/Paris': 'Europe/Paris',
  'UTC + 01:00 Europe/Podgorica': 'Europe/Podgorica',
  'UTC + 01:00 Europe/Prague': 'Europe/Prague',
  'UTC + 02:00 Europe/Riga': 'Europe/Riga',
  'UTC + 01:00 Europe/Rome': 'Europe/Rome',
  'UTC + 04:00 Europe/Samara': 'Europe/Samara',
  'UTC + 01:00 Europe/San Marino': 'Europe/San_Marino',
  'UTC + 01:00 Europe/Sarajevo': 'Europe/Sarajevo',
  'UTC + 02:00 Europe/Simferopol': 'Europe/Simferopol',
  'UTC + 01:00 Europe/Skopje': 'Europe/Skopje',
  'UTC + 02:00 Europe/Sofia': 'Europe/Sofia',
  'UTC + 01:00 Europe/Stockholm': 'Europe/Stockholm',
  'UTC + 02:00 Europe/Tallinn': 'Europe/Tallinn',
  'UTC + 01:00 Europe/Tirane': 'Europe/Tirane',
  'UTC + 02:00 Europe/Tiraspol': 'Europe/Tiraspol',
  'UTC + 02:00 Europe/Uzhgorod': 'Europe/Uzhgorod',
  'UTC + 01:00 Europe/Vaduz': 'Europe/Vaduz',
  'UTC + 01:00 Europe/Vatican': 'Europe/Vatican',
  'UTC + 01:00 Europe/Vienna': 'Europe/Vienna',
  'UTC + 02:00 Europe/Vilnius': 'Europe/Vilnius',
  'UTC + 01:00 Europe/Andorra': 'Europe/Andorra',
  'UTC + 02:00 Europe/Athens': 'Europe/Athens',
  'UTC + 00:00 Europe/Belfast': 'Europe/Belfast',
  'UTC + 01:00 Europe/Belgrade': 'Europe/Belgrade',
  'UTC + 01:00 Europe/Berlin': 'Europe/Berlin',
  'UTC + 01:00 Europe/Bratislava': 'Europe/Bratislava',
  'UTC + 01:00 Europe/Brussels': 'Europe/Brussels',
  'UTC + 02:00 Europe/Bucharest': 'Europe/Bucharest',
  'UTC + 01:00 Europe/Budapest': 'Europe/Budapest',
  'UTC + 02:00 Europe/Chisinau': 'Europe/Chisinau',
  'UTC + 01:00 Europe/Warsaw': 'Europe/Warsaw',
  'UTC + 01:00 Europe/Zagreb': 'Europe/Zagreb',
  'UTC + 02:00 Europe/Zaporozhye': 'Europe/Zaporozhye',
  'UTC + 01:00 Europe/Zurich': 'Europe/Zurich',
};

describe('match timezone with description', () => {
  test('match all timezones with description', () => {
    Object.keys(timezones).forEach(timezone => {
      const result = getLocationFromTimeZone(timezone);
      expect(result).toEqual(timezones[timezone]);
      spacetime()
        .goto(result)
        .startOf('day')
        .add(1, 'day')
        .add(8, 'hour')
        .goto('utc')
        .toNativeDate();
    });
  });
});
