name: Development Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    outputs:
      changed-front: ${{ steps.changed-front.outputs.changed }}
      changed-extension: ${{ steps.changed-extension.outputs.changed }}
      artifact-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Grant private repo access
        run: echo "${{ secrets.NPMRC_GITHUB }}" > .npmrc
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build sources
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run build
      #      - name: Update the versions
      #        env:
      #          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #        run: |
      #          git config user.name "${{ github.actor }}"
      #          git config user.email "${{ github.actor}}@users.noreply.github.com"
      #          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
      #      - uses: EndBug/add-and-commit@v9
      #        name: Commit version changes
      #        with:
      #          message: Version bump [skip-ci]
      #          committer_name: GitHub Actions
      #          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
      - uses: marceloprado/has-changed-path@v1
        name: Check if the extension has changed
        id: changed-extension
        with:
          paths: packages/apps/bloobirds-chrome-extension
      - name: Build production frontend app
        run: |
          cd packages/apps/bloobirds-platform-frontend
          npm run build:dev
      - name: Archive frontend build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: packages/apps/bloobirds-platform-frontend/build
      - name: Archive extension build artifact
        uses: actions/upload-artifact@v2
        id: artifact-upload-step
        if: steps.changed-extension.outputs.changed == 'true'
        with:
          name: dist-prod
          path: packages/apps/bloobirds-chrome-extension/dist
  release-frontend:
    name: Release frontend
    needs: build
    uses: ./.github/workflows/dev-app-release.yaml
    secrets: inherit
  upload_dist_extension:
    name: Upload Artifact and Comment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: marceloprado/has-changed-path@v1
        name: Check if the extension has changed
        id: changed-front
        with:
          paths: packages/apps/bloobirds-chrome-extension
      - name: Install dependencies
        if: steps.changed-front.outputs.changed == 'true'
        run: npm install
      - name: Build dev
        run: npm run extension:build:dev
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Upload dev dist artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: dist-dev
          path: packages/apps/bloobirds-chrome-extension/dist
