name: Generate Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Determine build command
        id: build_command
        run: |
          if [[ "${{ github.ref_name }}" == *-* ]]; then
            echo "build_command=extension:build:beta" >> $GITHUB_ENV
          else
            echo "build_command=extension:build:release" >> $GITHUB_ENV
          fi

      - name: Build the project
        run: npm run $build_command

      - name: Read changelog entry
        id: changelog
        run: |
          VERSION=$(echo "${GITHUB_REF#refs/tags/}")
          CHANGELOG_ENTRY=$(awk "/^## ${VERSION}/,/^## / { print }" CHANGELOG.md)
          echo "changelog=${CHANGELOG_ENTRY}" >> $GITHUB_OUTPUT

      - name: Upload dist artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: packages/apps/bloobirds-chrome-extension/dist

      - name: Commpress dist artifact
        run: tar -czvf packages/apps/bloobirds-chrome-extension/dist.tar.gz packages/apps/bloobirds-chrome-extension/dist

      - name: Create a new release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/apps/bloobirds-chrome-extension/dist/dist.tar.gz
          prerelease: ${{ contains(github.ref_name, '-') }}
          body: ${{ steps.changelog.outputs.changelog }}
