name: Generate Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Determine build command
        id: build_command
        run: |
          if [[ "${{ github.ref_name }}" == *-* ]]; then
            echo "build_command=extension:build:beta" >> $GITHUB_ENV
          else
            echo "build_command=extension:build:release" >> $GITHUB_ENV
          fi

      - name: Build the project
        run: npm run $build_command

      - name: Upload dist artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: packages/apps/bloobirds-chrome-extension/dist

      - name: Extract latest changelog entry
        id: changelog
        run: |
          latest_entry=$(awk '/^## \[/{flag=0} flag; /^## \[/{flag=1}' CHANGELOG.md)
          latest_entry="${latest_entry//'%'/'%25'}"
          latest_entry="${latest_entry//$'\n'/'%0A'}"
          latest_entry="${latest_entry//$'\r'/'%0D'}"
          echo "entry::$latest_entry" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # Utiliza solo el nombre del tag
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.entry }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }} # Detecta si es una pre-release

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
          asset_path: packages/apps/bloobirds-chrome-extension/dist
          asset_name: dist.zip
          asset_content_type: application/zip
