name: Generate Beta Version

on:
  push:
    branches:
      - production

jobs:
  create_beta_version:
    if: contains(github.event.head_commit.message, 'Prerelease')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'

      # - name: Install dependencies
      #   run: npm install

      - name: Generate changelog
        run: npm run changelog

      - name: Extract version from commit message
        id: extract_version
        run: |
          TITLE="${{ github.event.head_commit.message }}"
          VERSION=$(echo "$TITLE" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update manifest.json
        run: |
          NAME="Bloobirds Beta"
          ICON="src/beta.png"

          if [ -z "$VERSION" ]; then
            echo "No version number found in the PR title."
            exit 1
          fi

          cd packages/apps/bloobirds-chrome-extension
          sed -i 's/"name": ".*"/"name": "$NAME"/' ./manifest.json
          sed -i 's/"default_icon": ".*"/"default_icon": "$ICON"/' ./manifest.json

      - name: Update package.json
        run: |
          VERSION=${{ env.VERSION }}
          git add *
          cd packages/apps/bloobirds-chrome-extension
          npm version $VERSION

      - name: Push commits and tags
        run: |
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new branch for testing
        run: |
          VERSION=${{ env.VERSION }}
          git checkout -b "v$VERSION"
          git push origin "v$VERSION"
