name: Production CI

on:
  pull_request:
    branches:
      - production

jobs:
  linting:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Grant private repo access
        run: echo "${{ secrets.NPMRC_GITHUB }}" > .npmrc
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check linting rules
        run: npm run lint
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Grant private repo access
        run: echo "${{ secrets.NPMRC_GITHUB }}" > .npmrc
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Jest tests
        run: npm run test:unit
